name: Rtype building test

on:
  push:
    branches:
      - main
      - make_repo

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        cmake_version: [3.27.5]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Get latest CMake version
        uses: lukka/get-cmake@latest

      - name: building
        run:  |
          sudo apt update -y
          sudo apt upgrade -y
          sudo apt-get install pkg-config libudev-dev libgl-dev libx11-xcb-dev libfontenc-dev libice-dev libsm-dev libxau-dev libxaw7-dev libxcomposite-dev libxcursor-dev libxdamage-dev libxext-dev libxfixes-dev libxi-dev libxinerama-dev libxkbfile-dev libxmu-dev libxmuu-dev libxpm-dev libxrandr-dev libxrender-dev libxres-dev libxss-dev libxt-dev libxtst-dev libxv-dev libxvmc-dev libxxf86vm-dev libxcb-render0-dev libxcb-render-util0-dev libxcb-xkb-dev libxcb-icccm4-dev libxcb-image0-dev libxcb-keysyms1-dev libxcb-randr0-dev libxcb-shape0-dev libxcb-sync-dev libxcb-xfixes0-dev libxcb-xinerama0-dev libxcb-dri3-dev uuid-dev libxcb-cursor-dev libxcb-util-dev -y
          pip install conan
          conan profile detect
          conan install . --build=missing -of=build
          cd build
          cmake -DCMAKE_BUILD_TYPE=Release ..
          make
      
  build-windows:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        cmake_version: [3.27.5]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Get latest CMake version
        uses: lukka/get-cmake@latest
      
      - name: building
        run:  |
          cd Make
          choco install conan -y
          import-Module $env:ChocolateyInstall\helpers\chocolateyProfile.psm1
          refreshenv
          conan profile detect
          conan install . --build=missing
          mkdir build
          cd build
          cmake .. -DCMAKE_BUILD_TYPE=Release
